site_name: Software Design
site_description: Workspace for learning pythonic software design.
repo_url: https://github.com/evansdoe/software-design

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: { icon: material/weather-night, name: Dark mode }
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: { icon: material/weather-sunny, name: Light mode }

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
